var allLanguages = {
	"ab" : {"appdf":"Abkhaz"},
	"aa" : {"appdf":"Afar"},
	"af" : {"appdf":"Afrikaans"},
	"ak" : {"appdf":"Akan"},
	"sq" : {"appdf":"Albanian"},
	"am" : {"appdf":"Amharic"},
	"ar" : {"appdf":"Arabic"},
	"ar_eg" : {"appdf":"Arabic (Egypt)"},
	"ar_il" : {"appdf":"Arabic (Israel)"},
	"an" : {"appdf":"Aragonese"},
	"hy" : {"appdf":"Armenian"},
	"as" : {"appdf":"Assamese"},
	"av" : {"appdf":"Avaric"},
	"ae" : {"appdf":"Avestan"},
	"ay" : {"appdf":"Aymara"},
	"az" : {"appdf":"Azerbaijani"},
	"bm" : {"appdf":"Bambara"},
	"ba" : {"appdf":"Bashkir"},
	"eu" : {"appdf":"Basque"},
	"be" : {"appdf":"Belarusian"},
	"bn" : {"appdf":"Bengali"},
	"bh" : {"appdf":"Bihari"},
	"bi" : {"appdf":"Bislama"},
	"bs" : {"appdf":"Bosnian"},
	"br" : {"appdf":"Breton"},
	"bg" : {"appdf":"Bulgarian"},
	"my" : {"appdf":"Burmese"},
	"ca" : {"appdf":"Catalan"},
	"ch" : {"appdf":"Chamorro"},
	"ce" : {"appdf":"Chechen"},
	"ny" : {"appdf":"Chichewa"},
	"zh" : {"appdf":"Chinese"},
	"zh_cn" : {"appdf":"Chinese (PRC)"},
	"zh_tw" : {"appdf":"Chinese (Taiwan)"},
	"cv" : {"appdf":"Chuvash"},
	"kw" : {"appdf":"Cornish"},
	"co" : {"appdf":"Corsican"},
	"cr" : {"appdf":"Cree"},
	"hr" : {"appdf":"Croatian"},
	"cs" : {"appdf":"Czech"},
	"da" : {"appdf":"Danish"},
	"dv" : {"appdf":"Divehi"},
	"nl" : {"appdf":"Dutch"},
	"nl_be" : {"appdf":"Dutch (Belgium)"},
	"nl_nl" : {"appdf":"Dutch (Netherlands)"},
	"dz" : {"appdf":"Dzongkha"},
	"en" : {"appdf":"English"},
	"en_us" : {"appdf":"English (US)"},
	"en_au" : {"appdf":"English (Australia)"},
	"en_gb" : {"appdf":"English (Britain)"},
	"en_cz" : {"appdf":"English (Canada)"},
	"en_nz" : {"appdf":"English (New Zealand)"},
	"en_sg" : {"appdf":"English (Singapore)"},
	"en_cd" : {"appdf":"English (Canada)"},
	"eo" : {"appdf":"Esperanto"},
	"et" : {"appdf":"Estonian"},
	"ee" : {"appdf":"Ewe"},
	"fo" : {"appdf":"Faroese"},
	"fj" : {"appdf":"Fijian"},
	"fi" : {"appdf":"Finnish"},
	"fr" : {"appdf":"French"},
	"fr_be" : {"appdf":"French (Belgium)"},
	"fr_ca" : {"appdf":"French (Canada)"},
	"fr_fr" : {"appdf":"French (France)"},
	"fr_ch" : {"appdf":"French (Switzerland)"},
	"ff" : {"appdf":"Fula"},
	"gl" : {"appdf":"Galician"},
	"ka" : {"appdf":"Georgian"},
	"de" : {"appdf":"German"},
	"de_at" : {"appdf":"German (Austria)"},
	"de_de" : {"appdf":"German (Germany)"},
	"de_li" : {"appdf":"German (Liechtenstein)"},
	"de_ch" : {"appdf":"German (Switzerland)"},
	"el" : {"appdf":"Greek"},
	"gn" : {"appdf":"Guaraní"},
	"gu" : {"appdf":"Gujarati"},
	"ht" : {"appdf":"Haitian"},
	"ha" : {"appdf":"Hausa"},
	"he" : {"appdf":"Hebrew"},
	"hz" : {"appdf":"Herero"},
	"hi" : {"appdf":"Hindi"},
	"ho" : {"appdf":"Hiri Motu"},
	"hu" : {"appdf":"Hungarian"},
	"ia" : {"appdf":"Interlingua"},
	"id" : {"appdf":"Indonesian"},
	"ie" : {"appdf":"Interlingue"},
	"ga" : {"appdf":"Irish"},
	"ig" : {"appdf":"Igbo"},
	"ik" : {"appdf":"Inupiaq"},
	"io" : {"appdf":"Ido"},
	"is" : {"appdf":"Icelandic"},
	"it" : {"appdf":"Italian"},
	"it_it" : {"appdf":"Italian (Italy)"},
	"it_ch" : {"appdf":"Italian (Switzerland)"},
	"iu" : {"appdf":"Inuktitut"},
	"ja" : {"appdf":"Japanese"},
	"jv" : {"appdf":"Javanese"},
	"kl" : {"appdf":"Kalaallisut"},
	"kn" : {"appdf":"Kannada"},
	"kr" : {"appdf":"Kanuri"},
	"ks" : {"appdf":"Kashmiri"},
	"kk" : {"appdf":"Kazakh"},
	"km" : {"appdf":"Khmer"},
	"ki" : {"appdf":"Kikuyu"},
	"rw" : {"appdf":"Kinyarwanda"},
	"ky" : {"appdf":"Kyrgyz"},
	"kv" : {"appdf":"Komi"},
	"kg" : {"appdf":"Kongo"},
	"ko" : {"appdf":"Korean"},
	"ku" : {"appdf":"Kurdish"},
	"kj" : {"appdf":"Kwanyama"},
	"la" : {"appdf":"Latin"},
	"lb" : {"appdf":"Luxembourgish"},
	"lg" : {"appdf":"Ganda"},
	"li" : {"appdf":"Limburgish"},
	"ln" : {"appdf":"Lingala"},
	"lo" : {"appdf":"Lao"},
	"lt" : {"appdf":"Lithuanian"},
	"lu" : {"appdf":"Luba-Katanga"},
	"lv" : {"appdf":"Latvian"},
	"gv" : {"appdf":"Manx"},
	"mk" : {"appdf":"Macedonian"},
	"mg" : {"appdf":"Malagasy"},
	"ms" : {"appdf":"Malay"},
	"ml" : {"appdf":"Malayalam"},
	"mt" : {"appdf":"Maltese"},
	"mi" : {"appdf":"Maori"},
	"mr" : {"appdf":"Marathi"},
	"mh" : {"appdf":"Marshallese"},
	"mn" : {"appdf":"Mongolian"},
	"na" : {"appdf":"Nauru"},
	"nv" : {"appdf":"Navajo"},
	"nb" : {"appdf":"Norwegian Bokmål"},
	"nd" : {"appdf":"North Ndebele"},
	"ne" : {"appdf":"Nepali"},
	"ng" : {"appdf":"Ndonga"},
	"nn" : {"appdf":"Norwegian Nynorsk"},
	"no" : {"appdf":"Norwegian"},
	"ii" : {"appdf":"Nuosu"},
	"nr" : {"appdf":"South Ndebele"},
	"oc" : {"appdf":"Occitan"},
	"oj" : {"appdf":"Ojibwe"},
	"om" : {"appdf":"Oromo"},
	"or" : {"appdf":"Oriya"},
	"os" : {"appdf":"Ossetian"},
	"pa" : {"appdf":"Panjabi"},
	"pi" : {"appdf":"Pāli"},
	"fa" : {"appdf":"Persian"},
	"pl" : {"appdf":"Polish"},
	"ps" : {"appdf":"Pashto"},
	"pt" : {"appdf":"Portuguese"},
	"pt_br" : {"appdf":"Portuguese (Brazil)"},
	"pt_pt" : {"appdf":"Portuguese (Portugal)"},
	"qu" : {"appdf":"Quechua"},
	"rm" : {"appdf":"Romansh"},
	"rn" : {"appdf":"Kirundi"},
	"ro" : {"appdf":"Romanian"},
	"ru" : {"appdf":"Russian"},
	"sa" : {"appdf":"Sanskrit"},
	"sc" : {"appdf":"Sardinian"},
	"sd" : {"appdf":"Sindhi"},
	"se" : {"appdf":"Northern Sami"},
	"sm" : {"appdf":"Samoan"},
	"sg" : {"appdf":"Sango"},
	"sr" : {"appdf":"Serbian"},
	"gd" : {"appdf":"Gaelic"},
	"sn" : {"appdf":"Shona"},
	"si" : {"appdf":"Sinhala"},
	"sk" : {"appdf":"Slovak"},
	"sl" : {"appdf":"Slovene"},
	"so" : {"appdf":"Somali"},
	"st" : {"appdf":"Southern Sotho"},
	"es" : {"appdf":"Spanish"},
	"es_es" : {"appdf":"Spanish (Spain)"},
	"es_us" : {"appdf":"Spanish (US)"},
	"es_la" : {"appdf":"Spanish (Latin America)"},
	"su" : {"appdf":"Sundanese"},
	"sw" : {"appdf":"Swahili"},
	"ss" : {"appdf":"Swati"},
	"sv" : {"appdf":"Swedish"},
	"ta" : {"appdf":"Tamil"},
	"te" : {"appdf":"Telugu"},
	"tg" : {"appdf":"Tajik"},
	"th" : {"appdf":"Thai"},
	"ti" : {"appdf":"Tigrinya"},
	"bo" : {"appdf":"Tibetan Standard"},
	"tk" : {"appdf":"Turkmen"},
	"tl" : {"appdf":"Tagalog"},
	"tn" : {"appdf":"Tswana"},
	"to" : {"appdf":"Tonga"},
	"tr" : {"appdf":"Turkish"},
	"ts" : {"appdf":"Tsonga"},
	"tt" : {"appdf":"Tatar"},
	"tw" : {"appdf":"Twi"},
	"ty" : {"appdf":"Tahitian"},
	"ug" : {"appdf":"Uighur"},
	"uk" : {"appdf":"Ukrainian"},
	"ur" : {"appdf":"Urdu"},
	"uz" : {"appdf":"Uzbek"},
	"ve" : {"appdf":"Venda"},
	"vi" : {"appdf":"Vietnamese"},
	"vo" : {"appdf":"Volapük"},
	"wa" : {"appdf":"Walloon"},
	"cy" : {"appdf":"Welsh"},
	"wo" : {"appdf":"Wolof"},
	"fy" : {"appdf":"Western Frisian"},
	"xh" : {"appdf":"Xhosa"},
	"yi" : {"appdf":"Yiddish"},
	"yo" : {"appdf":"Yoruba"},
	"za" : {"appdf":"Zhuang"},
	"zu" : {"appdf":"Zulu"}
};

var googleLanguages = ["English (United States)",
"Afrikaans",
"Amharic",
"Arabic",
"Belarusian",
"Bulgarian",
"Catalan",
"Chinese (Simplified)",
"Chinese (Traditional)",
"Croatian",
"Czech",
"Danish",
"Dutch",
"English (United Kingdom)",
"Estonian",
"Filipino",
"Finnish",
"French",
"German",
"Greek",
"Hebrew",
"Hindi",
"Hungarian",
"Italian",
"Japanese",
"Korean (South Korea)",
"Latvian",
"Lithuanian",
"Malay",
"Norwegian",
"Persian",
"Polish",
"Portuguese (Brazil)",
"Portuguese (Portugal)",
"Romanian",
"Romansh",
"Russian",
"Serbian",
"Slovak",
"Slovenian",
"Spanish (Latin America)",
"Spanish (Spain)",
"Spanish (United States)",
"Swahili",
"Swedish",
"Thai",
"Turkish",
"Ukrainian",
"Vietnamese",
"Zulu",];

var allAmazon = [
"English (U.K.)",
"French",
"German",
"Italian",
"Spanish",
"Japanese",
"Chinese (Simplified)"
]

var allOpera = [
"ENGLISH", 
"RUSSIAN", 
"GERMAN", 
"ITALIAN", 
"FRENCH", 
"SPANISH", 
"DUTCH", 
"TURKISH", 
"SWEDISH", 
"DANISH", 
"CHINESE", 
"GREEK", 
"PORTUGUESE", 
"CZECH", 
"SLOVAK", 
"POLISH", 
"INDONESIA", 
"VIETNAMESE", 
"NORWAY", 
"BENGALI", 
"FARSI", 
"HUNGARIAN", 
"JAPANESE", 
"KOREAN", 
"MALAY", 
"NEPALESE", 
"ROMANIAN", 
"TAGALOG", 
"THAI",
"ARABIC"
];

var allYandex = [
"English",
"Russian",
"German",
"Italian",
"French",
"Spanish",
"Dutch",
"Turkish",
"Swedish",
"Danish",
"Chinese",
"Greek",
"Portuguese",
"Czech",
"Slovak",
"Polish",
"Indonesia",
"Vietnamese",
"Norway",
"Bengali",
"Farsi",
"Hungarian",
"Japanese",
"Korean",
"Malay",
"Nepalese",
"Romanian",
"Tagalog",
"Thai",
"Arabic"
];

var allSamsung = [
"Arabic", 
"Bulgarian", 
"Croatian", 
"Czech",
"Danish", 
"Dutch", 
"Estonian", 
"Finnish",
"French", 
"Gaelic", 
"German", 
"Greek",
"Hebrew", 
"Hungarian", 
"Indonesian", 
"Italian",
"Japanese", 
"Kazakh", 
"Korean", 
"Latvian",
"Lithuanian", 
"Norwegian", 
"Persian", 
"Polish",
"Portuguese", 
"Romanian", 
"Russian",   
"Serbian",
"Simplified Chinese", 
"Slovak", 
"Spanish", 
"Swedish",
"Thai", 
"Traditional Chinese", 
"Turkish",
"Ukrainian",
"Vietnamese"
];